// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "Return the most recent leads captured by the HydrAI Labs website (audit form, contact form, landings). Requires an admin account \u2014 non-admin users receive an empty list due to row-level security.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of leads to return (default 20)."),
    status: z.enum(["new", "contacted", "qualified", "proposal", "won", "lost"]).optional().describe("Optional status filter.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("leads").select("id, name, email, phone, status, priority, score, source, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-assessments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_assessments_default = defineTool2({
  name: "list_assessments",
  title: "List diagnostic assessments",
  description: "Return the latest self-diagnostic assessments submitted through /auditoria and /auditoria-gratis. Admin-only via row-level security.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum number of assessments to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("assessments").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assessments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "Return HydrAI Labs blog posts (title, slug, excerpt, published state). Useful for content planning and cross-linking suggestions.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of posts (default 20)."),
    only_published: z3.boolean().optional().describe("If true, return only published posts.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, only_published }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let query = sb.from("blog_posts").select("id, title, slug, excerpt, published, published_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_published) query = query.eq("published", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tshfnwdqidyhfajzovnq";
var mcp_default = defineMcp({
  name: "hydrailabs-mcp",
  title: "HydrAI Labs MCP",
  version: "0.1.0",
  instructions: "Tools for the HydrAI Labs website. Use `list_leads` to inspect recent leads, `list_assessments` for diagnostic submissions, and `list_blog_posts` for content planning. All tools act as the signed-in user and respect row-level security (admin access required for leads and assessments).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, list_assessments_default, list_blog_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
