import type { VerticalConfig } from "./VerticalLandingPage";

export const verticalConfigs: Record<string, VerticalConfig> = {
  "chatbot-whatsapp-restaurantes-malaga": {
    slug: "chatbot-whatsapp-restaurantes-malaga",
    vertical: "Restaurantes",
    city: "Málaga",
    badge: "Restaurantes · Málaga",
    seoTitle: "Chatbot WhatsApp para Restaurantes en Málaga | HydrAI Labs",
    metaDescription: "Chatbot IA en WhatsApp para restaurantes en Málaga: gestiona reservas, menú, pedidos y reseñas 24/7 en varios idiomas. Auditoría gratuita.",
    keywords: "chatbot WhatsApp restaurantes Málaga, chatbot reservas restaurante, IA restaurantes Málaga, automatización restaurantes WhatsApp",
    h1Top: "Chatbot WhatsApp",
    h1Bottom: "para restaurantes en Málaga",
    heroSubline: "Gestiona reservas, dudas del menú, pedidos y reseñas en WhatsApp 24/7 sin que tu equipo deje de servir mesas. Multilingüe, integrado con tu sistema de reservas.",
    problem:
      "En Málaga el ritmo del servicio no permite que un camarero deje de atender mesas para responder WhatsApp. El resultado: reservas perdidas, dudas sin contestar, reseñas tibias y mucho turista que decide en otro restaurante porque no respondiste a tiempo.",
    solution:
      "Implementamos un chatbot IA en WhatsApp Business conectado a tu sistema de reservas (Covermanager, TheFork u otro), tu menú y tu equipo. Responde en segundos, en varios idiomas, gestiona reservas reales y solo escala a humano cuando aporta valor.",
    features: [
      { title: "Reservas automáticas", desc: "Confirma huecos, registra la reserva en tu sistema y envía recordatorios anti no-show por WhatsApp." },
      { title: "Menú y alérgenos", desc: "Responde dudas del menú, alérgenos, opciones veganas o sin gluten al instante." },
      { title: "Pedidos para llevar", desc: "Toma pedidos take-away o delivery directamente en WhatsApp con confirmación de pago." },
      { title: "Multilingüe", desc: "Inglés, español, alemán, francés. Responde en el idioma del cliente automáticamente." },
      { title: "Gestión de reseñas", desc: "Pide reseñas tras la visita y deriva quejas al manager antes de que lleguen a Google." },
      { title: "Métricas claras", desc: "Dashboard con reservas confirmadas, tasa de respuesta y conversión por canal." },
    ],
    workflow: [
      { step: "1", title: "Cliente escribe por WhatsApp", desc: "Llega una consulta de reserva, menú o pedido a tu número de WhatsApp Business." },
      { step: "2", title: "El agente IA entiende e identifica", desc: "Detecta intención (reservar, preguntar, quejarse) e idioma del cliente." },
      { step: "3", title: "Consulta disponibilidad real", desc: "Se conecta a tu sistema de reservas y propone huecos reales en función de aforo." },
      { step: "4", title: "Confirma y registra", desc: "Confirma la reserva, la guarda en tu sistema y envía recordatorio el día previo." },
      { step: "5", title: "Escala si hace falta", desc: "Si el cliente pide algo fuera de protocolo (grupo grande, evento), avisa al manager." },
    ],
    impact: [
      { value: "+40%", label: "Reservas captadas vía WhatsApp" },
      { value: "−70%", label: "Tiempo dedicado a responder dudas" },
      { value: "24/7", label: "Atención en cualquier idioma" },
    ],
    forWho: [
      "Restaurantes con +30 reservas/semana en Málaga",
      "Equipos pequeños que no llegan al WhatsApp",
      "Negocios con alto % de turismo internacional",
      "Locales que quieren reducir no-shows",
    ],
    notForWho: [
      "Negocios sin canal WhatsApp activo",
      "Restaurantes que no aceptan reservas",
      "Quien busca atención 100% humana sin automatizar nada",
    ],
    faqItems: [
      { question: "¿Funciona con mi sistema de reservas actual?", answer: "Integramos con Covermanager, TheFork, Resy, Google Calendar y APIs propias. Si tu sistema tiene API o webhook, lo conectamos." },
      { question: "¿En cuántos idiomas responde?", answer: "Por defecto español, inglés, alemán y francés. Podemos añadir más bajo demanda." },
      { question: "¿Cuánto tarda la implementación?", answer: "Entre 5 y 10 días laborables, incluyendo integración con tu sistema de reservas y formación." },
      { question: "¿Sustituye a mi personal?", answer: "No. Libera al equipo de las dudas repetitivas para que se centren en el servicio en sala." },
      { question: "¿Cuánto cuesta?", answer: "Desde 297 €/mes según volumen. La auditoría inicial es gratuita." },
    ],
  },

  "automatizacion-ia-clinicas-esteticas-malaga": {
    slug: "automatizacion-ia-clinicas-esteticas-malaga",
    vertical: "Clínicas estéticas",
    city: "Málaga",
    badge: "Clínicas estéticas · Málaga",
    seoTitle: "Automatización IA para Clínicas Estéticas en Málaga | HydrAI Labs",
    metaDescription: "Automatización con IA para clínicas estéticas en Málaga: agenda automática, recordatorios anti no-show, captación de leads y fidelización por WhatsApp.",
    keywords: "automatización IA clínicas estéticas Málaga, agentes IA clínicas estética, chatbot clínica estética, agenda automática clínica Málaga",
    h1Top: "Automatización IA",
    h1Bottom: "para clínicas estéticas en Málaga",
    heroSubline: "Agenda automática, recordatorios anti no-show, captación de leads desde redes sociales y fidelización por WhatsApp. Diseñado para clínicas que quieren llenar su agenda sin saturar a recepción.",
    problem:
      "Las clínicas estéticas en Málaga pierden facturación por dos motivos clásicos: no-shows que dejan huecos sin cubrir y leads de Instagram o Facebook Ads que tardan horas en ser contactados. Cuando recepción por fin responde, el cliente ya ha cerrado con la competencia.",
    solution:
      "Implementamos un sistema completo: chatbot IA en WhatsApp e Instagram que cualifica leads en segundos, recordatorios automáticos 48h y 2h antes para reducir no-shows, integración con tu agenda (Flowww, Bookitit, calendario propio) y campañas de fidelización segmentadas.",
    features: [
      { title: "Agenda automática", desc: "El bot consulta huecos reales y reserva directamente en Flowww, Bookitit o tu calendario." },
      { title: "Anti no-show", desc: "Recordatorios 48h y 2h antes con confirmación. Reduce no-shows hasta un 60%." },
      { title: "Captación Instagram/Meta", desc: "Cualifica leads de Ads en segundos vía WhatsApp y los pasa al CRM." },
      { title: "Campañas de fidelización", desc: "Segmentación por tratamiento y envío de promos relevantes, no spam." },
      { title: "Cumple RGPD", desc: "Doble opt-in, consentimiento explícito y borrado bajo demanda." },
      { title: "Dashboard de clínica", desc: "Conversión por anuncio, ocupación de agenda, no-shows y revenue por tratamiento." },
    ],
    workflow: [
      { step: "1", title: "Lead llega por Ads o web", desc: "Click desde Meta Ads, web o WhatsApp directo a la clínica." },
      { step: "2", title: "Cualificación automática", desc: "El agente IA pregunta tratamiento de interés, urgencia y disponibilidad." },
      { step: "3", title: "Propuesta de cita real", desc: "Consulta huecos en tu agenda y propone 2-3 opciones concretas." },
      { step: "4", title: "Confirmación y CRM", desc: "Reserva la cita y guarda al lead cualificado en el CRM." },
      { step: "5", title: "Recordatorios anti no-show", desc: "Envía recordatorios automáticos para minimizar ausencias." },
      { step: "6", title: "Seguimiento post-tratamiento", desc: "Pide reseña, propone retoque o tratamiento complementario." },
    ],
    impact: [
      { value: "−60%", label: "Reducción de no-shows" },
      { value: "+35%", label: "Conversión de leads de Ads" },
      { value: "<2 min", label: "Tiempo de respuesta medio" },
    ],
    forWho: [
      "Clínicas estéticas con +200 citas/mes en Málaga",
      "Centros que invierten en Meta Ads",
      "Clínicas con problemas de no-shows",
      "Equipos de recepción saturados de WhatsApp",
    ],
    notForWho: [
      "Clínicas sin agenda digital",
      "Negocios sin volumen mínimo de leads",
      "Quien no quiera cumplir RGPD",
    ],
    faqItems: [
      { question: "¿Es legal automatizar WhatsApp con datos de pacientes?", answer: "Sí, implementamos doble opt-in y consentimiento explícito. Los datos se tratan según RGPD y no compartimos información clínica sensible por canal no seguro." },
      { question: "¿Funciona con Flowww o Bookitit?", answer: "Sí, integramos con los principales softwares de gestión clínica vía API." },
      { question: "¿Cuánto reduce los no-shows?", answer: "En clínicas similares vemos reducciones del 40-60% con recordatorios bien diseñados y confirmación obligatoria." },
      { question: "¿Cuánto tarda en estar operativo?", answer: "Entre 7 y 14 días según número de tratamientos y complejidad de integración." },
      { question: "¿Cuánto cuesta?", answer: "Desde 397 €/mes según volumen y nº de profesionales. Auditoría inicial gratuita." },
    ],
  },

  "agentes-ia-inmobiliarias-costa-del-sol": {
    slug: "agentes-ia-inmobiliarias-costa-del-sol",
    vertical: "Inmobiliarias",
    city: "Costa del Sol",
    badge: "Inmobiliarias · Costa del Sol",
    seoTitle: "Agentes IA para Inmobiliarias en Costa del Sol | HydrAI Labs",
    metaDescription: "Agentes IA para inmobiliarias en Costa del Sol: cualificación automática de compradores, scraping de leads, respuestas multilingüe y CRM integrado.",
    keywords: "agentes IA inmobiliarias Costa del Sol, IA inmobiliaria Marbella, chatbot inmobiliaria multilingüe, automatización captación inmobiliaria",
    h1Top: "Agentes IA",
    h1Bottom: "para inmobiliarias en Costa del Sol",
    heroSubline: "Cualifica automáticamente compradores internacionales en su idioma, conecta con tu CRM y dedica el tiempo de tus agentes solo a leads listos para visitar.",
    problem:
      "En la Costa del Sol los leads vienen de muchos canales (Idealista, Fotocasa, Kyero, Rightmove, Meta Ads, web propia) y en muchos idiomas. La mayoría de agencias responden tarde, sin cualificar y sin diferenciar al curioso del comprador real. Resultado: agentes quemados persiguiendo a quien nunca va a comprar.",
    solution:
      "Implementamos agentes IA que reciben leads de todos los portales, los cualifican en su idioma (presupuesto, zona, plazos, financiación), los puntúan y solo los pasan al agente humano cuando están listos para visita. Todo integrado con tu CRM (HubSpot, Inmovilla, Witei).",
    features: [
      { title: "Multilingüe nativo", desc: "Inglés, alemán, francés, sueco, español. El agente conversa en el idioma del cliente." },
      { title: "Cualificación automática", desc: "Presupuesto, zona, tipo, plazos, financiación, residencia. Score automático de calidad." },
      { title: "Integración con portales", desc: "Recibe leads de Idealista, Fotocasa, Kyero, Rightmove vía email parsing o API." },
      { title: "CRM conectado", desc: "Vuelca leads a HubSpot, Inmovilla, Witei o tu CRM con score, idioma e historial." },
      { title: "Agendamiento de visitas", desc: "Reserva visitas en el calendario del agente cuando el lead está listo." },
      { title: "Seguimiento automático", desc: "Nurturing por WhatsApp/email para leads no listos hasta que estén." },
    ],
    workflow: [
      { step: "1", title: "Llega lead de portal", desc: "Idealista, Kyero, Rightmove, Meta Ads o web envían un nuevo lead." },
      { step: "2", title: "Detección de idioma", desc: "El agente IA detecta el idioma y abre conversación inmediata por WhatsApp/email." },
      { step: "3", title: "Cualificación", desc: "Pregunta presupuesto, zona deseada, plazos, residencia y necesidad de financiación." },
      { step: "4", title: "Scoring y derivación", desc: "Si el lead supera el umbral, se asigna a un agente humano con todo el contexto." },
      { step: "5", title: "Agendamiento de visita", desc: "El bot propone huecos del agente asignado y confirma la visita." },
      { step: "6", title: "Nurturing si no está listo", desc: "Envíos automáticos de propiedades nuevas que cuadran con sus criterios." },
    ],
    impact: [
      { value: "+50%", label: "Leads cualificados aprovechados" },
      { value: "−65%", label: "Tiempo perdido por agente" },
      { value: "5 idiomas", label: "Atención simultánea" },
    ],
    forWho: [
      "Inmobiliarias con +100 leads/mes",
      "Agencias con clientela internacional",
      "Equipos pequeños que no escalan",
      "Agencias en Marbella, Estepona, Mijas",
    ],
    notForWho: [
      "Agencias sin CRM activo",
      "Inmobiliarias sin web ni canal digital",
      "Quien no quiera cualificar leads",
    ],
    faqItems: [
      { question: "¿Funciona con Idealista, Kyero y Rightmove?", answer: "Sí. Recibimos leads vía parsing de email o API según portal y los procesamos en segundos." },
      { question: "¿Cualifica en alemán, inglés y francés?", answer: "Sí, soporta inglés, alemán, francés, sueco, neerlandés y español de forma nativa." },
      { question: "¿Se integra con mi CRM?", answer: "Sí: HubSpot, Inmovilla, Witei, Zoho, Salesforce y CRMs propios vía API." },
      { question: "¿El cliente nota que es un bot?", answer: "El tono es natural y siempre se identifica como asistente. La derivación a humano es transparente." },
      { question: "¿Cuánto cuesta?", answer: "Desde 497 €/mes según volumen de leads y nº de agentes. Auditoría gratuita." },
    ],
  },

  "chatbot-ia-hoteles-marbella": {
    slug: "chatbot-ia-hoteles-marbella",
    vertical: "Hoteles",
    city: "Marbella",
    badge: "Hoteles · Marbella",
    seoTitle: "Chatbot IA para Hoteles en Marbella | HydrAI Labs",
    metaDescription: "Chatbot IA multilingüe para hoteles en Marbella: pre-stay, in-stay y post-stay automatizados en WhatsApp. Aumenta upsell y reduce carga de recepción.",
    keywords: "chatbot IA hoteles Marbella, chatbot hotel WhatsApp, conserjería digital hotel, automatización hotel Marbella",
    h1Top: "Chatbot IA",
    h1Bottom: "para hoteles en Marbella",
    heroSubline: "Conserjería digital 24/7 en WhatsApp: pre-stay, check-in, in-stay y post-stay totalmente automatizados. Aumenta el upsell y libera a recepción.",
    problem:
      "En hoteles boutique y resorts de Marbella, recepción se ahoga gestionando consultas básicas en WhatsApp, email y teléfono: hora de check-in, transfer, reservas de restaurante, servicios de spa. Mientras, el upsell se queda sin vender porque nadie tiene tiempo de proponerlo.",
    solution:
      "Implementamos un chatbot IA multilingüe integrado con tu PMS y servicios internos. Resuelve el 80% de las consultas habituales, propone upgrades, vende experiencias y solo escala a recepción los casos que aportan valor.",
    features: [
      { title: "Multilingüe premium", desc: "Inglés, español, alemán, francés, ruso, árabe. Tono adaptado a hotel premium." },
      { title: "Pre-stay automático", desc: "Confirma reserva, ofrece transfer, propone upgrade y reserva de restaurante." },
      { title: "Check-in digital", desc: "Recoge datos de huéspedes, documentos y preferencias antes de llegar." },
      { title: "In-stay 24/7", desc: "Resuelve dudas del hotel, reservas internas y peticiones especiales en WhatsApp." },
      { title: "Upsell inteligente", desc: "Propone spa, restaurante, excursiones según perfil y momento de la estancia." },
      { title: "Post-stay y reseñas", desc: "Encuesta de satisfacción y derivación inteligente: contentos a TripAdvisor, descontentos a manager." },
    ],
    workflow: [
      { step: "1", title: "Reserva confirmada", desc: "El huésped recibe un WhatsApp de bienvenida con info clave y opciones de upsell." },
      { step: "2", title: "Pre-stay", desc: "Días antes: oferta de transfer, upgrade, reservas de restaurante o spa." },
      { step: "3", title: "Check-in digital", desc: "El día de llegada, recogida de datos y documentos para acelerar el check-in físico." },
      { step: "4", title: "In-stay", desc: "Atiende dudas y peticiones (toallas, hora de spa, taxi) sin pasar por recepción." },
      { step: "5", title: "Upsell contextual", desc: "Propone experiencias según comportamiento y duración de la estancia." },
      { step: "6", title: "Post-stay", desc: "Encuesta NPS, derivación de reseñas y campaña de retorno." },
    ],
    impact: [
      { value: "−50%", label: "Carga de recepción en WhatsApp" },
      { value: "+25%", label: "Conversión de upsell" },
      { value: "6 idiomas", label: "Atención nativa multilingüe" },
    ],
    forWho: [
      "Hoteles boutique y 4-5* en Marbella",
      "Resorts con servicios cruzados (spa, restaurante)",
      "Hoteles con clientela internacional",
      "Equipos de recepción saturados",
    ],
    notForWho: [
      "Apartamentos turísticos sin servicios extra",
      "Hoteles sin PMS digital",
      "Quien no quiera medir NPS ni upsell",
    ],
    faqItems: [
      { question: "¿Se integra con mi PMS?", answer: "Sí: Mews, Cloudbeds, Opera, Protel y otros vía API o conector intermedio." },
      { question: "¿En cuántos idiomas?", answer: "6 idiomas nativos (EN, ES, DE, FR, RU, AR) y ampliables bajo demanda." },
      { question: "¿Reemplaza a recepción?", answer: "No. Libera a recepción del 80% de consultas repetitivas para que se centre en huéspedes presenciales y casos complejos." },
      { question: "¿Cuánto tarda la implementación?", answer: "Entre 10 y 20 días según integraciones y volumen de servicios cruzados." },
      { question: "¿Cuánto cuesta?", answer: "Plan a medida según nº de habitaciones e integraciones. Auditoría inicial gratuita." },
    ],
  },

  "automatizacion-ia-pymes-malaga": {
    slug: "automatizacion-ia-pymes-malaga",
    vertical: "Pymes",
    city: "Málaga",
    badge: "Pymes · Málaga",
    seoTitle: "Automatización IA para Pymes en Málaga | HydrAI Labs",
    metaDescription: "Automatización con IA para pymes en Málaga: chatbots, agentes IA, flujos n8n y dashboards. Implementación rápida y ROI medible. Auditoría gratuita.",
    keywords: "automatización IA pymes Málaga, IA para pymes Málaga, agencia IA Málaga, automatización procesos pyme",
    h1Top: "Automatización IA",
    h1Bottom: "para pymes en Málaga",
    heroSubline: "Automatiza la atención al cliente, la captación de leads y los procesos internos sin necesidad de equipo técnico. Implementación en 5-10 días con resultados medibles.",
    problem:
      "Las pymes de Málaga llegan a un techo claro: el dueño y un equipo pequeño hacen de todo. Cada hora dedicada a tareas repetitivas (responder WhatsApp, pasar datos entre Excel y CRM, hacer presupuestos, perseguir cobros) es una hora que no se dedica a vender ni a mejorar el servicio.",
    solution:
      "Diseñamos un sistema de automatización a medida con chatbots, agentes IA y flujos n8n que conectan tus herramientas (WhatsApp, CRM, email, calendario, contabilidad). Sin código por tu parte, con dashboards que te muestran qué está funcionando.",
    features: [
      { title: "Chatbot WhatsApp 24/7", desc: "Responde, cualifica y deriva consultas comerciales en cualquier momento." },
      { title: "CRM automatizado", desc: "Leads, seguimientos y tareas se crean solos en HubSpot, Pipedrive o Zoho." },
      { title: "Generación de documentos", desc: "Presupuestos, contratos y facturas generadas y enviadas automáticamente." },
      { title: "Cobros y recordatorios", desc: "Flujos automáticos de cobro y recordatorio de facturas vencidas." },
      { title: "Reporting", desc: "Dashboards con KPIs comerciales, operativos y financieros en tiempo real." },
      { title: "Integraciones", desc: "n8n + APIs: conectamos cualquier herramienta que ya uses." },
    ],
    workflow: [
      { step: "1", title: "Auditoría", desc: "Detectamos los procesos manuales que más tiempo consumen y mayor ROI tienen." },
      { step: "2", title: "Diseño", desc: "Plan claro: qué se automatiza, en qué orden, con qué herramientas y a qué coste." },
      { step: "3", title: "Implementación", desc: "Montamos chatbots, agentes IA y flujos n8n integrados con tus herramientas." },
      { step: "4", title: "Formación", desc: "Tu equipo aprende a usar y supervisar el sistema. Documentación incluida." },
      { step: "5", title: "Iteración", desc: "Soporte continuo y ajustes según métricas y nuevas necesidades." },
    ],
    impact: [
      { value: "+15h", label: "Ahorro semanal medio" },
      { value: "+30%", label: "Conversión de leads" },
      { value: "5-10 días", label: "Tiempo de implementación" },
    ],
    forWho: [
      "Pymes de Málaga con 2-30 empleados",
      "Negocios con CRM o herramientas digitales activas",
      "Equipos saturados por tareas repetitivas",
      "Dueños que quieren escalar sin contratar más",
    ],
    notForWho: [
      "Negocios sin volumen mínimo de operaciones",
      "Quien no quiera cambiar ningún proceso interno",
      "Empresas sin presupuesto recurrente para sistemas",
    ],
    faqItems: [
      { question: "¿Necesito conocimientos técnicos?", answer: "No. Diseñamos, implementamos y mantenemos. Tu equipo aprende a usar el sistema con formación incluida." },
      { question: "¿Qué herramientas integráis?", answer: "WhatsApp Business, HubSpot, Pipedrive, Zoho, Notion, Google Workspace, Microsoft 365, Holded, Stripe, n8n y APIs propias." },
      { question: "¿Cuánto cuesta?", answer: "Implementaciones desde 1.500 € + cuota mensual desde 297 €. Plan personalizado según alcance." },
      { question: "¿Cuánto tarda?", answer: "Entre 5 y 10 días laborables para la primera fase." },
      { question: "¿Y si no funciona?", answer: "Definimos KPIs claros antes de empezar. Si no se cumplen, iteramos sin coste extra hasta lograrlos." },
    ],
  },
};
